"""Validate the pairing-to-ring-class transfer at toy scale.

Sub-goal: P1.5 / SG-33
Inputs:   [--smoke] [--output-dir PATH]
Outputs:  data/probe_ring_class_transfer_<profile>_<date>.csv
Runtime:  smoke under 10 seconds
Validated against: the conductor exact sequence for Z[p*i] and the existing
                   embedding-degree-two pairing fixtures
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
from datetime import date
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(0, str(REPOSITORY_ROOT))

from lib.curves import embedding_degree, is_prime, supersingular_k2_curve  # noqa: E402
from lib.dlog import multiplicative_bsgs  # noqa: E402
from lib.extension_curves import ExtensionCurve, ExtensionPoint  # noqa: E402
from lib.finite_fields import ExtensionElement, ExtensionField  # noqa: E402
from lib.isogeny import reduced_positive_forms  # noqa: E402
from lib.pairing import (  # noqa: E402
    j1728_distortion_map,
    lift_base_point,
    reduced_tate_pairing,
)

Form = tuple[int, int, int]
GaussianInteger = tuple[int, int]

SMOKE_CASES = ((43, 11, 7),)
FULL_CASES = ((43, 11, 7), (211, 53, 37), (331, 83, 37))


def reduce_positive_form(form: Form) -> Form:
    """Return the canonical reduced representative of a positive form."""
    a, b, c = form
    discriminant = b * b - 4 * a * c
    if a <= 0 or discriminant >= 0 or math.gcd(math.gcd(a, abs(b)), c) != 1:
        raise ValueError("form must be primitive and positive definite")

    for _ in range(10_000):
        shift = (a - b) // (2 * a)
        if shift:
            c = a * shift * shift + b * shift + c
            b = b + 2 * a * shift
        if a > c:
            a, b, c = c, -b, a
            continue
        if abs(b) <= a <= c:
            if b < 0 and (abs(b) == a or a == c):
                b = -b
            result = (a, b, c)
            if b * b - 4 * a * c != discriminant:
                raise ArithmeticError("form reduction changed the discriminant")
            return result
        a, b, c = c, -b, a
    raise ArithmeticError("positive-form reduction did not terminate")


def ring_class_form_from_parameter(p: int, parameter: int | None) -> Form:
    """Map a projective residue [1:t], or infinity, into Pic(Z[p*i])."""
    if not is_prime(p) or p % 4 != 3:
        raise ValueError("p must be prime and congruent to 3 modulo 4")
    if parameter is None:
        return (1, 0, p * p)
    t = parameter % p
    raw = (1 + t * t, 2 * p * t, p * p)
    if raw[1] * raw[1] - 4 * raw[0] * raw[2] != -4 * p * p:
        raise ArithmeticError("ring-class form has the wrong discriminant")
    return reduce_positive_form(raw)


def projective_parameter(value: ExtensionElement) -> int | None:
    """Return t for the F_p-projective residue class [1:t]."""
    if not value:
        raise ValueError("projective residue must be nonzero")
    if value.field.degree != 2 or value.field.modulus != (1, 0, 1):
        raise ValueError("expected F_p[i] with i^2 = -1")
    real, imaginary = value.coefficients
    if real == 0:
        return None
    return imaginary * pow(real, -1, value.field.q) % value.field.q


def ring_class_form_from_value(value: ExtensionElement) -> Form:
    """Map a nonzero F_(p^2) residue to its ordinary ring ideal class."""
    return ring_class_form_from_parameter(value.field.q, projective_parameter(value))


def _nearest_integer(numerator: int, denominator: int) -> int:
    """Round an exact rational to a nearest integer."""
    if denominator <= 0:
        raise ValueError("denominator must be positive")
    sign = -1 if numerator < 0 else 1
    quotient, remainder = divmod(abs(numerator), denominator)
    if 2 * remainder >= denominator:
        quotient += 1
    return sign * quotient


def gaussian_remainder(
    dividend: GaussianInteger, divisor: GaussianInteger
) -> GaussianInteger:
    """Return a Euclidean remainder in Z[i]."""
    a, b = dividend
    c, d = divisor
    norm = c * c + d * d
    if norm == 0:
        raise ZeroDivisionError("Gaussian divisor is zero")
    quotient_real = _nearest_integer(a * c + b * d, norm)
    quotient_imaginary = _nearest_integer(b * c - a * d, norm)
    product_real = quotient_real * c - quotient_imaginary * d
    product_imaginary = quotient_real * d + quotient_imaginary * c
    return a - product_real, b - product_imaginary


def gaussian_gcd(left: GaussianInteger, right: GaussianInteger) -> GaussianInteger:
    """Return a generator of the ideal generated by two Gaussian integers."""
    while right != (0, 0):
        left, right = right, gaussian_remainder(left, right)
    if left == (0, 0):
        return left
    candidates = (
        left,
        (-left[1], left[0]),
        (-left[0], -left[1]),
        (left[1], -left[0]),
    )
    return min(candidates)


def torus_invariant_from_form(
    p: int, form: Form, field: ExtensionField
) -> ExtensionElement:
    """Convert a reduced ring-class form to a unit-independent torus value."""
    a, b, c = form
    if b * b - 4 * a * c != -4 * p * p or b % 2:
        raise ValueError("form is not in the discriminant -4*p^2 class group")
    generator = gaussian_gcd((a, 0), (-b // 2, p))
    residue = field.element((generator[0] % p, generator[1] % p))
    if not residue:
        raise ArithmeticError("extended ideal generator is zero modulo the conductor")
    return residue ** (2 * (p - 1))


def validate_exact_sequence(p: int) -> tuple[int, int]:
    """Check that projective residues exhaust Pic(Z[p*i]) two-to-one."""
    discriminant = -4 * p * p
    expected = set(reduced_positive_forms(discriminant))
    observed = {
        ring_class_form_from_parameter(p, parameter)
        for parameter in (*range(p), None)
    }
    if observed != expected:
        raise ArithmeticError("residue-class images do not equal the full ring class group")
    if len(observed) != (p + 1) // 2:
        raise ArithmeticError("ring class number disagrees with the conductor formula")
    return len(observed), len(expected)


def pairing_context(
    p: int, subgroup_order: int
) -> tuple[ExtensionField, ExtensionCurve, ExtensionPoint, ExtensionPoint]:
    """Build the standard j=1728 embedding-degree-two pairing context."""
    if not is_prime(p) or not is_prime(subgroup_order):
        raise ValueError("p and subgroup order must be prime")
    curve, generator, _ = supersingular_k2_curve(p, subgroup_order)
    if embedding_degree(p, subgroup_order) != 2:
        raise ValueError("subgroup must have embedding degree two")
    field = ExtensionField(p, (1, 0, 1))
    extension_curve = ExtensionCurve(field, field.element(1), field.zero)
    source_generator = lift_base_point(field, generator)
    distorted = j1728_distortion_map(field, generator, field.element((0, 1)))
    if not extension_curve.contains(source_generator) or not extension_curve.contains(distorted):
        raise ArithmeticError("pairing context contains an invalid point")
    return field, extension_curve, source_generator, distorted


def run_case(p: int, subgroup_order: int, secret: int) -> dict[str, object]:
    """Validate one complete pairing-to-ring-class transfer instance."""
    field, curve, generator, distorted = pairing_context(p, subgroup_order)

    def pairing_image(point: ExtensionPoint) -> ExtensionElement:
        if point is None:
            return field.one
        return reduced_tate_pairing(curve, subgroup_order, point, distorted)

    generator_value = pairing_image(generator)
    if generator_value == field.one or generator_value**subgroup_order != field.one:
        raise ArithmeticError("pairing generator image does not have the required order")

    forms: list[Form] = []
    torus_values: list[ExtensionElement] = []
    for scalar in range(subgroup_order):
        point = curve.scalar_mul(scalar, generator)
        value = pairing_image(point)
        if value != generator_value**scalar:
            raise ArithmeticError("pairing image is not homomorphic")
        form = ring_class_form_from_value(value)
        if form[1] * form[1] - 4 * form[0] * form[2] != -4 * p * p:
            raise ArithmeticError("output left the fixed ring class group")
        forms.append(form)
        torus_values.append(torus_invariant_from_form(p, form, field))

        unit_multiple = value * field.element((0, 1))
        if ring_class_form_from_value(unit_multiple) != form:
            raise ArithmeticError("Gaussian-unit quotient is not respected")

    if len(set(forms)) != subgroup_order:
        raise ArithmeticError("ring-class transfer is not injective")
    if forms[0] != (1, 0, p * p):
        raise ArithmeticError("source identity did not map to the principal class")
    if torus_values[0] != field.one:
        raise ArithmeticError("principal class did not map to the torus identity")
    if any(
        value != torus_values[1] ** scalar
        for scalar, value in enumerate(torus_values)
    ):
        raise ArithmeticError("form-to-torus conversion is not homomorphic on the image")

    target = curve.scalar_mul(secret, generator)
    target_form = ring_class_form_from_value(pairing_image(target))
    target_torus = torus_invariant_from_form(p, target_form, field)
    recovered = multiplicative_bsgs(
        torus_values[1], target_torus, subgroup_order
    )
    if recovered != secret:
        raise ArithmeticError("ring-class image did not preserve the source scalar")

    class_number, enumerated = validate_exact_sequence(p)
    return {
        "p": p,
        "r": subgroup_order,
        "secret": secret,
        "recovered": recovered,
        "discriminant": -4 * p * p,
        "discriminant_bits": (4 * p * p).bit_length(),
        "class_number": class_number,
        "enumerated_forms": enumerated,
        "image_size": len(set(forms)),
        "generator_form_a": forms[1][0],
        "generator_form_b": forms[1][1],
        "generator_form_c": forms[1][2],
        "target_form_a": target_form[0],
        "target_form_b": target_form[1],
        "target_form_c": target_form[2],
    }


def write_rows(rows: list[dict[str, object]], path: Path) -> None:
    """Write deterministic validation rows."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--smoke", action="store_true")
    parser.add_argument("--output-dir", type=Path, default=Path(__file__).parents[1] / "data")
    args = parser.parse_args()
    cases = SMOKE_CASES if args.smoke else FULL_CASES
    rows = [run_case(*case) for case in cases]
    profile = "smoke" if args.smoke else "full"
    output = args.output_dir / f"probe_ring_class_transfer_{profile}_{date.today():%Y%m%d}.csv"
    write_rows(rows, output)
    for row in rows:
        print(row)
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
