"""
measure_corrected_cases.py -- certify quotient and CM Koblitz constants.
Sub-goal: P5.1 / SG-05, SG-08
Inputs:   --limit <int> --checkpoints <csv> --product-limit <int> --seed <int>
Outputs:  data/measure_corrected_cases_x<limit>_l<product-limit>_s<seed>_<date>.csv
Runtime:  about 9 s wall time at limit=2^17 on the recorded host
Validated against: LMFDB 540.f2 adelic generators and Zywina 2011, Lemma 7.1
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
import time
from collections import deque
from dataclasses import dataclass
from datetime import date
from fractions import Fraction
from functools import lru_cache
from pathlib import Path

CODE_DIR = Path(__file__).resolve().parent
if str(CODE_DIR) not in sys.path:
    sys.path.insert(0, str(CODE_DIR))

from measure_density import (
    CURVES,
    CurveSpec,
    exact_order,
    parse_checkpoints,
    poisson_style_constant_interval,
    primes_up_to,
    universal_koblitz_product,
)
from lib.curves import is_prime


PUBLISHED_CM_CONSTANT = 1.067350894

TORSION_3 = next(spec for spec in CURVES if spec.key == "torsion_3")
CM_CURVE = CurveSpec(
    key="cm_j1728",
    label="y^2=x^3-x over Q(i), split rational primes",
    a=-1,
    b=0,
    rational_torsion_order=8,
    bad_primes=frozenset({2}),
    constant_rule="zywina_cm_qi_t8",
)

# LMFDB 540.f2, adelic image 30.16.0-30.b.1.4, accessed 2026-06-29.
ADELIC_GENERATORS_MOD_30 = (
    (6, 1, 13, 24),
    (1, 0, 6, 1),
    (4, 3, 9, 7),
    (7, 6, 21, 19),
    (25, 6, 24, 7),
    (3, 4, 8, 11),
    (1, 6, 0, 1),
)

Matrix = tuple[int, int, int, int]


@dataclass(frozen=True, slots=True)
class FiniteLevelCertificate:
    group_order_mod_30: int
    group_order_mod_90: int
    favorable_mod_90: int
    density: Fraction
    low_prime_multiplier: Fraction
    universal_correction: Fraction


def matrix_multiply(left: Matrix, right: Matrix, modulus: int) -> Matrix:
    """Multiply two row-major 2-by-2 matrices modulo modulus."""
    a, b, c, d = left
    e, f, g, h = right
    return (
        (a * e + b * g) % modulus,
        (a * f + b * h) % modulus,
        (c * e + d * g) % modulus,
        (c * f + d * h) % modulus,
    )


def matrix_inverse(matrix: Matrix, modulus: int) -> Matrix:
    """Invert a matrix whose determinant is a unit modulo modulus."""
    a, b, c, d = matrix
    determinant = (a * d - b * c) % modulus
    inverse_determinant = pow(determinant, -1, modulus)
    return (
        d * inverse_determinant % modulus,
        -b * inverse_determinant % modulus,
        -c * inverse_determinant % modulus,
        a * inverse_determinant % modulus,
    )


@lru_cache(maxsize=1)
def adelic_group_mod_30() -> frozenset[Matrix]:
    """Enumerate the subgroup generated by the certified LMFDB matrices."""
    modulus = 30
    generators = list(ADELIC_GENERATORS_MOD_30)
    steps = generators + [matrix_inverse(item, modulus) for item in generators]
    identity = (1, 0, 0, 1)
    group = {identity}
    frontier = deque([identity])
    while frontier:
        current = frontier.popleft()
        for step in steps:
            candidate = matrix_multiply(current, step, modulus)
            if candidate not in group:
                group.add(candidate)
                frontier.append(candidate)
    return frozenset(group)


@lru_cache(maxsize=1)
def torsion_3_finite_level_certificate() -> FiniteLevelCertificate:
    """Count Psi_3(90) in the full level-90 inverse image of G(30)."""
    group_mod_30 = adelic_group_mod_30()
    favorable = 0
    for a0, b0, c0, d0 in group_mod_30:
        for a_lift in range(3):
            a = a0 + 30 * a_lift
            for b_lift in range(3):
                b = b0 + 30 * b_lift
                for c_lift in range(3):
                    c = c0 + 30 * c_lift
                    for d_lift in range(3):
                        d = d0 + 30 * d_lift
                        determinant_i_minus_a = (
                            (1 - a) * (1 - d) - b * c
                        ) % 90
                        if math.gcd(determinant_i_minus_a, 90) == 3:
                            favorable += 1

    order_mod_90 = len(group_mod_30) * 3**4
    density = Fraction(favorable, order_mod_90)
    low_denominator = Fraction(1, 2) * Fraction(2, 3) * Fraction(4, 5)
    low_prime_multiplier = density / low_denominator

    universal_low_factors = Fraction(1, 1)
    for ell in (2, 3, 5):
        universal_low_factors *= 1 - Fraction(
            ell * ell - ell - 1, (ell - 1) ** 3 * (ell + 1)
        )
    universal_correction = low_prime_multiplier / universal_low_factors
    return FiniteLevelCertificate(
        group_order_mod_30=len(group_mod_30),
        group_order_mod_90=order_mod_90,
        favorable_mod_90=favorable,
        density=density,
        low_prime_multiplier=low_prime_multiplier,
        universal_correction=universal_correction,
    )


def torsion_3_quotient_constant(prime_limit: int) -> float:
    """Return the certified truncated C_(E,3) for LMFDB curve 540.f2."""
    if prime_limit < 5:
        raise ValueError("prime_limit must include the exceptional primes 2, 3, 5")
    certificate = torsion_3_finite_level_certificate()
    return float(certificate.universal_correction) * universal_koblitz_product(
        prime_limit
    )


def quadratic_character_minus_four(ell: int) -> int:
    """Return the nonzero quadratic character modulo 4 at an odd prime."""
    if ell == 2:
        return 0
    return 1 if ell % 4 == 1 else -1


def cm_qi_t8_constant(prime_limit: int) -> float:
    """Truncate Zywina's absolutely convergent product for C_(E_Q(i),8)."""
    product = 4.0 / math.pi
    for ell in primes_up_to(prime_limit):
        if ell == 2:
            continue
        character = quadratic_character_minus_four(ell)
        local_factor = 1.0 - character * (ell * ell - ell - 1) / (
            (ell - character) * (ell - 1) ** 2
        )
        product *= local_factor / (1.0 - character / ell)
    return product


def generic_full_gl2_t8_constant(prime_limit: int) -> float:
    """Return the deliberately inapplicable full-GL(2) t=8 benchmark."""
    if prime_limit < 2:
        raise ValueError("prime_limit must include 2")
    modulus = 16
    group_order = 0
    favorable = 0
    for a in range(modulus):
        for b in range(modulus):
            for c in range(modulus):
                for d in range(modulus):
                    if math.gcd(a * d - b * c, modulus) != 1:
                        continue
                    group_order += 1
                    if ((1 - a) * (1 - d) - b * c) % modulus == 8:
                        favorable += 1
    density = Fraction(favorable, group_order)
    low_prime_multiplier = density / Fraction(1, 2)
    universal_factor_at_2 = Fraction(2, 3)
    correction = low_prime_multiplier / universal_factor_at_2
    return float(correction) * universal_koblitz_product(prime_limit)


def refined_weight(prime: int, quotient: int) -> float:
    """Return the prime-sum form of Zywina's refined finite-x weight."""
    if prime + 1 <= quotient:
        return 0.0
    denominator = math.log(prime + 1.0) - math.log(quotient)
    return 1.0 / denominator


def result_row(
    *,
    case_key: str,
    curve: CurveSpec,
    quotient: int,
    cutoff: int,
    eligible_prime_count: int,
    quotient_prime_count: int,
    baseline: float,
    constant: float,
    exhaustive_fallback_count: int,
    elapsed_seconds: float,
    seed: int,
    invalid_pool_count: int | None = None,
    invalid_pool_baseline: float | None = None,
    invalid_pool_constant: float | None = None,
) -> dict[str, object]:
    """Construct one deterministic measurement row."""
    predicted = constant * baseline
    measured = quotient_prime_count / baseline
    ci_low, ci_high = poisson_style_constant_interval(
        quotient_prime_count, baseline
    )
    ratio = quotient_prime_count / predicted
    invalid_predicted = (
        invalid_pool_baseline * invalid_pool_constant
        if invalid_pool_baseline is not None and invalid_pool_constant is not None
        else math.nan
    )
    invalid_ratio = (
        invalid_pool_count / invalid_predicted
        if invalid_pool_count is not None and invalid_predicted
        else math.nan
    )
    return {
        "case_key": case_key,
        "curve": curve.label,
        "quotient": quotient,
        "cutoff": cutoff,
        "eligible_prime_count": eligible_prime_count,
        "exhaustive_fallback_count": exhaustive_fallback_count,
        "quotient_prime_count": quotient_prime_count,
        "refined_baseline": f"{baseline:.12f}",
        "predicted_constant": f"{constant:.12f}",
        "predicted_count": f"{predicted:.12f}",
        "measured_constant": f"{measured:.12f}",
        "constant_ci95_low": f"{ci_low:.12f}",
        "constant_ci95_high": f"{ci_high:.12f}",
        "observed_over_predicted": f"{ratio:.12f}",
        "invalid_pool_count": "" if invalid_pool_count is None else invalid_pool_count,
        "invalid_pool_baseline": (
            "" if invalid_pool_baseline is None else f"{invalid_pool_baseline:.12f}"
        ),
        "invalid_pool_constant": (
            "" if invalid_pool_constant is None else f"{invalid_pool_constant:.12f}"
        ),
        "invalid_pool_predicted": (
            "" if not math.isfinite(invalid_predicted) else f"{invalid_predicted:.12f}"
        ),
        "invalid_pool_observed_over_predicted": (
            "" if not math.isfinite(invalid_ratio) else f"{invalid_ratio:.12f}"
        ),
        "elapsed_seconds": f"{elapsed_seconds:.6f}",
        "seed": seed,
        "point_counter": "hasse_bsgs_twist_with_exact_fallback",
    }


def measure(
    limit: int,
    checkpoints: list[int],
    product_limit: int,
    seed: int,
) -> list[dict[str, object]]:
    """Measure the certified non-CM quotient and CM split-prime cases."""
    primes = [prime for prime in primes_up_to(limit) if prime > 3]
    rows: list[dict[str, object]] = []
    quotient_3_constant = torsion_3_quotient_constant(product_limit)
    cm_constant = cm_qi_t8_constant(product_limit)
    invalid_full_gl_constant = generic_full_gl2_t8_constant(product_limit)

    started = time.perf_counter()
    position = 0
    eligible = count = fallback = 0
    baseline = 0.0
    for cutoff in checkpoints:
        while position < len(primes) and primes[position] <= cutoff:
            prime = primes[position]
            position += 1
            if prime in TORSION_3.bad_primes:
                continue
            order, method = exact_order(TORSION_3, prime, seed, 2)
            eligible += 1
            fallback += method == "exhaustive_fallback"
            baseline += refined_weight(prime, 3)
            if order % 3 == 0 and is_prime(order // 3):
                count += 1
        rows.append(
            result_row(
                case_key="torsion_3_quotient",
                curve=TORSION_3,
                quotient=3,
                cutoff=cutoff,
                eligible_prime_count=eligible,
                quotient_prime_count=count,
                baseline=baseline,
                constant=quotient_3_constant,
                exhaustive_fallback_count=fallback,
                elapsed_seconds=time.perf_counter() - started,
                seed=seed,
            )
        )

    started = time.perf_counter()
    position = 0
    split_eligible = split_count = pooled_count = fallback = 0
    split_baseline = pooled_baseline = 0.0
    for cutoff in checkpoints:
        while position < len(primes) and primes[position] <= cutoff:
            prime = primes[position]
            position += 1
            if prime in CM_CURVE.bad_primes:
                continue
            order, method = exact_order(CM_CURVE, prime, seed, 3)
            fallback += method == "exhaustive_fallback"
            weight = refined_weight(prime, 8)
            pooled_baseline += weight
            is_quotient_prime = order % 8 == 0 and is_prime(order // 8)
            pooled_count += is_quotient_prime
            if prime % 4 == 1:
                split_eligible += 1
                split_baseline += weight
                split_count += is_quotient_prime
        rows.append(
            result_row(
                case_key="cm_qi_split_t8",
                curve=CM_CURVE,
                quotient=8,
                cutoff=cutoff,
                eligible_prime_count=split_eligible,
                quotient_prime_count=split_count,
                baseline=split_baseline,
                constant=cm_constant,
                exhaustive_fallback_count=fallback,
                elapsed_seconds=time.perf_counter() - started,
                seed=seed,
                invalid_pool_count=pooled_count,
                invalid_pool_baseline=pooled_baseline,
                invalid_pool_constant=invalid_full_gl_constant,
            )
        )
    return rows


def write_csv(rows: list[dict[str, object]], output: Path) -> None:
    """Write rows with deterministic column order."""
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def plot_rows(rows: list[dict[str, object]], output: Path) -> None:
    """Plot corrected ratios and the intentionally invalid pooled benchmark."""
    import matplotlib.pyplot as plt

    by_case: dict[str, list[dict[str, object]]] = {}
    for row in rows:
        by_case.setdefault(str(row["case_key"]), []).append(row)

    figure, axes = plt.subplots(1, 2, figsize=(11.5, 4.4))
    palette = {"torsion_3_quotient": "#735aa6", "cm_qi_split_t8": "#0b6e69"}
    for axis, case_key, title in (
        (axes[0], "torsion_3_quotient", "Non-CM: rational 3-torsion"),
        (axes[1], "cm_qi_split_t8", "CM: split primes over Q(i)"),
    ):
        case_rows = by_case[case_key]
        x_values = [int(row["cutoff"]) for row in case_rows]
        ratios = [float(row["observed_over_predicted"]) for row in case_rows]
        axis.plot(
            x_values,
            ratios,
            marker="o",
            linewidth=2,
            color=palette[case_key],
            label="corrected refined predictor",
        )
        axis.axhline(1.0, color="#d2553d", linestyle="--", linewidth=1.4)
        axis.set_xscale("log", base=2)
        axis.set_xlabel("Prime cutoff x")
        axis.set_ylabel("Observed / predicted")
        axis.set_title(title)
        axis.grid(alpha=0.25)
        axis.legend(frameon=False, fontsize=9)

    cm_rows = by_case["cm_qi_split_t8"]
    axes[1].plot(
        [int(row["cutoff"]) for row in cm_rows],
        [float(row["invalid_pool_observed_over_predicted"]) for row in cm_rows],
        marker="s",
        linestyle=":",
        linewidth=1.8,
        color="#c08a2d",
        label="invalid pooled full-GL(2) benchmark",
    )
    axes[1].legend(frameon=False, fontsize=9)
    figure.suptitle("P5.1 -- certified quotient and CM-specific constants", fontsize=13)
    figure.tight_layout()
    output.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(output, dpi=180, bbox_inches="tight")
    plt.close(figure)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, default=1 << 15)
    parser.add_argument(
        "--checkpoints",
        default="1024,2048,4096,8192,16384,32768,65536,131072",
    )
    parser.add_argument("--product-limit", type=int, default=1_000_000)
    parser.add_argument("--seed", type=int, default=51012026)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--figure", type=Path)
    parser.add_argument("--no-plot", action="store_true")
    parser.add_argument("--smoke", action="store_true")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    if args.smoke:
        args.limit = 512
        args.checkpoints = "128,256,512"
        args.product_limit = 10_000
    if args.limit < 11:
        raise ValueError("limit must be at least 11 for the t=8 refined weight")
    if args.limit.bit_length() > 18:
        raise ValueError("limit exceeds the session's toy ceiling of 2^17")

    checkpoints = parse_checkpoints(args.checkpoints, args.limit)
    rows = measure(args.limit, checkpoints, args.product_limit, args.seed)
    stamp = date.today().strftime("%Y%m%d")
    stem = (
        f"measure_corrected_cases_x{args.limit}_l{args.product_limit}"
        f"_s{args.seed}_{stamp}"
    )
    output = args.output or (Path(__file__).parents[1] / "data" / f"{stem}.csv")
    figure = args.figure or (Path(__file__).parents[1] / "figures" / f"{stem}.png")
    write_csv(rows, output)
    if not args.no_plot:
        plot_rows(rows, figure)

    certificate = torsion_3_finite_level_certificate()
    print(f"group_order_mod_30={certificate.group_order_mod_30}")
    print(f"group_order_mod_90={certificate.group_order_mod_90}")
    print(f"favorable_mod_90={certificate.favorable_mod_90}")
    print(f"delta_E_3_90={certificate.density}")
    print(f"universal_correction_E_3={certificate.universal_correction}")
    print(
        "torsion_3_quotient_constant="
        f"{torsion_3_quotient_constant(args.product_limit):.15f}"
    )
    print(f"cm_qi_t8_constant={cm_qi_t8_constant(args.product_limit):.15f}")
    print(f"csv={output}")
    if not args.no_plot:
        print(f"figure={figure}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
