"""
observe_mov_transfer.py — trace a toy MOV-style Tate-pairing transfer.
Sub-goal: P1.1 / validation
Inputs:   --p 43 --trials 1 --seed 0
Outputs:  data/observe_mov_transfer_p43_r11_20260626.csv
Runtime:  under 1 second at p=43 and subgroup order 11
Validated against: published F_43 Tate values and the bilinearity identity
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from lib.extension_curves import ExtensionCurve
from lib.finite_fields import ExtensionElement, ExtensionField
from lib.pairing import (
    j1728_distortion_map,
    lift_base_point,
    miller_loop_with_trace,
    reduced_tate_pairing,
)


def small_multiplicative_dlog(
    base: ExtensionElement,
    target: ExtensionElement,
    order: int,
) -> tuple[int, int]:
    """Return the exponent and equality tests in a tiny cyclic subgroup."""
    value = base.field.one
    for exponent in range(order):
        if value == target:
            return exponent, exponent + 1
        value = value * base
    raise ValueError("target is not in the subgroup generated by base")


def run() -> dict[str, int | str]:
    field = ExtensionField(43, (1, 0, 1))
    curve = ExtensionCurve(field, field.element(1), field.zero)
    order = 11
    secret = 2
    point = lift_base_point(field, (23, 8))
    auxiliary = j1728_distortion_map(field, (23, 8), field.element((0, 1)))
    target = curve.scalar_mul(secret, point)

    raw_base, base_trace = miller_loop_with_trace(curve, order, point, auxiliary)
    raw_target, target_trace = miller_loop_with_trace(curve, order, target, auxiliary)
    base_value = reduced_tate_pairing(curve, order, point, auxiliary)
    target_value = reduced_tate_pairing(curve, order, target, auxiliary)
    recovered, equality_tests = small_multiplicative_dlog(
        base_value, target_value, order
    )

    if base_value != field.element((11, 3)):
        raise ArithmeticError("base pairing disagrees with the fixed vector")
    if target_value != field.element((26, 23)):
        raise ArithmeticError("doubled pairing disagrees with the fixed vector")
    if target_value != base_value**secret or recovered != secret:
        raise ArithmeticError("pairing transfer did not preserve the logarithm")

    return {
        "p": field.q,
        "extension_degree": field.degree,
        "curve": "y^2=x^3+x",
        "subgroup_order": order,
        "embedding_degree": 2,
        "secret": secret,
        "recovered": recovered,
        "raw_pairing_base": str(raw_base),
        "raw_pairing_target": str(raw_target),
        "reduced_pairing_base": str(base_value),
        "reduced_pairing_target": str(target_value),
        "pairing_evaluations": 2,
        "miller_line_evaluations": len(base_trace) + len(target_trace),
        "target_group_equality_tests": equality_tests,
        "extension_group_scalar_multiplications": 1,
        "auxiliary_dlp_solves": 1,
        "p_adic_lifts": 0,
        "polynomial_system_solves": 0,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--p", type=int, default=43)
    parser.add_argument("--trials", type=int, default=1)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--smoke", action="store_true")
    args = parser.parse_args()
    if args.p != 43 or args.trials != 1:
        raise ValueError("the validated fixture supports only --p 43 --trials 1")
    row = run()
    output = (
        Path(__file__).resolve().parents[1]
        / "data"
        / "observe_mov_transfer_p43_r11_20260626.csv"
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(row))
        writer.writeheader()
        writer.writerow(row)
    print(output)
    print(row)


if __name__ == "__main__":
    main()
